export const OBTER_PROJETOS = "OBTER_PROJETOS"
export const CADASTAR_PROJETOS = "CADASTAR_PROJETOS"
export const ALTERAR_PROJETOS = "ALTERAR_PROJETOS"
export const REMOVER_PROJETOS = "REMOVER_PROJETOS"