export const OBTER_PROJETOS = "OBTER_PROJETO"
export const CADASTAR_PROJETO = "CADASTAR_PROJETO"
export const ALTERAR_PROJETO = "ALTERAR_PROJETO"
export const REMOVER_PROJETO = "REMOVER_PROJETO"

export const OBTER_TAREFAS = "OBTER_TAREFA"
export const CADASTAR_TAREFA = "CADASTAR_TAREFA"
export const ALTERAR_TAREFA = "ALTERAR_TAREFA"
export const REMOVER_TAREFA = "REMOVER_TAREFA"